# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vald/v1/filter/ingress/ingress_filter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vald.v1.payload import payload_pb2 as vald_dot_v1_dot_payload_dot_payload__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vald/v1/filter/ingress/ingress_filter.proto',
  package='filter.ingress.v1',
  syntax='proto3',
  serialized_options=b'\n$org.vdaas.vald.api.v1.filter.ingressB\021ValdIngressFilterP\001Z1github.com/vdaas/vald/apis/grpc/v1/filter/ingress',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+vald/v1/filter/ingress/ingress_filter.proto\x12\x11\x66ilter.ingress.v1\x1a\x1dvald/v1/payload/payload.proto\x1a\x1cgoogle/api/annotations.proto2\xd5\x01\n\x06\x46ilter\x12\x62\n\tGenVector\x12\x17.payload.v1.Object.Blob\x1a\x19.payload.v1.Object.Vector\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/filter/ingress/object:\x01*\x12g\n\x0c\x46ilterVector\x12\x19.payload.v1.Object.Vector\x1a\x19.payload.v1.Object.Vector\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/filter/ingress/vector:\x01*Bn\n$org.vdaas.vald.api.v1.filter.ingressB\x11ValdIngressFilterP\x01Z1github.com/vdaas/vald/apis/grpc/v1/filter/ingressb\x06proto3'
  ,
  dependencies=[vald_dot_v1_dot_payload_dot_payload__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_FILTER = _descriptor.ServiceDescriptor(
  name='Filter',
  full_name='filter.ingress.v1.Filter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=128,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenVector',
    full_name='filter.ingress.v1.Filter.GenVector',
    index=0,
    containing_service=None,
    input_type=vald_dot_v1_dot_payload_dot_payload__pb2._OBJECT_BLOB,
    output_type=vald_dot_v1_dot_payload_dot_payload__pb2._OBJECT_VECTOR,
    serialized_options=b'\202\323\344\223\002\033\"\026/filter/ingress/object:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FilterVector',
    full_name='filter.ingress.v1.Filter.FilterVector',
    index=1,
    containing_service=None,
    input_type=vald_dot_v1_dot_payload_dot_payload__pb2._OBJECT_VECTOR,
    output_type=vald_dot_v1_dot_payload_dot_payload__pb2._OBJECT_VECTOR,
    serialized_options=b'\202\323\344\223\002\033\"\026/filter/ingress/vector:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILTER)

DESCRIPTOR.services_by_name['Filter'] = _FILTER

# @@protoc_insertion_point(module_scope)
